
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from tkinter import font
import subprocess


# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import time
import pyotp
from email.message import EmailMessage
import smtplib

def send_email(message,recipient):
    me = "wildwhispers12@gmail.com"

    msg = EmailMessage()
    msg['Subject'] = "New Message"
    msg['From'] = me
    msg['To'] = recipient
    msg.set_content(f"""\
    Greetings from the Wild Whispers team! 🌿

    Thank you for choosing Wild Whispers for your authentication needs. Your One-Time Password (OTP) is:

    {message}

    Please use this OTP to complete your authentication process. If you did not request this OTP, please ignore this message.

    If you have any questions or need further assistance, feel free to reach out to us.

    Best Regards,
    The Wild Whispers Team
    """)

    server = smtplib.SMTP_SSL('smtp.gmail.com', 465)
    server.login("wildwhispers12@gmail.com", "qkoy lnqv pozt qysa")
    server.send_message(msg)
    server.quit()
    window.destroy()
    subprocess.run(["python", "client.py"])
    

key = "WildWhispers"
totp = pyotp.TOTP(key)
# print(totp.now())

# input_code = input("Enter your code:")
# print(totp.verify(input_code))


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Academics\Chat Application\build3\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)
def on_button_click():
    recipient = entry_1.get()
    message = totp.now()
    send_email(message, recipient)



window = Tk()

window.geometry("400x400")
window.configure(bg = "#EAE2EE")


canvas = Canvas(
    window,
    bg = "#EAE2EE",
    height = 400,
    width = 400,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    206.0,
    235.0,
    image=image_image_1
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=on_button_click,
    relief="flat"
)
button_1.place(
    x=147.0,
    y=136.0,
    width=94.0,
    height=30.0
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    200.0,
    110.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#ACBED8",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=42.0,
    y=93.0,
    width=316.0,
    height=32.0
)

canvas.create_text(
    85.0,
    25.0,
    anchor="nw",
    text="AUTHENTICATION",
    fill="#FFFFFF",
    font=font.Font(family="Galindo",size=24 * -1,weight="bold")
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    203.5,
    72.0,
    image=entry_image_2
)

window.resizable(False, False)
window.mainloop()
