
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from tkinter import font

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH_FOR_FAQ = OUTPUT_PATH / Path(r"C:\Academics\Chat Application\build2\assets\frame0")


def relative_to_assets_for_faq(path: str) -> Path:
    return ASSETS_PATH_FOR_FAQ / Path(path)


adar = Tk()

adar.geometry("600x600")
adar.configure(bg = "#EAE2EE")


canvas = Canvas(
    adar,
    bg = "#EAE2EE",
    height = 600,
    width = 600,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets_for_faq("image_1.png"))
image_1 = canvas.create_image(
    300.0,
    300.0,
    image=image_image_1
)

canvas.create_text(
    10.0,
    32.0,
    anchor="nw",
    text="FREQUENTLY ASKED QUESTIONS\n                     (FAQ)",
    fill="#FFFFFF",
   font=font.Font(family="Galindo",size=32 * -1,weight="bold")
)

button_image_1 = PhotoImage(
    file=relative_to_assets_for_faq("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=6.0,
    y=289.0,
    width=589.0,
    height=65.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets_for_faq("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=6.0,
    y=144.0,
    width=589.0,
    height=46.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets_for_faq("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=6.0,
    y=452.0,
    width=589.0,
    height=67.0
)
adar.resizable(False, False)
adar.mainloop()
